### ISSUE TITLE
Support referencing tuple file in the store file

### ISSUE THREAD

**Issue by rhamzeh** [openfga/vscode-ext#144]
Currently, we support a `model_file` option in addition to `model` for users who prefer to edit their model in a separate file.

We should support a `tuple_file` that does the same for tuples.

That file will be the same format as accepted by `write`

```yaml
name: Some Store
model_file: ./model.fga
tuple_file: ./tuples.yaml
tests:
  - name: test 1
    tuple_file: ./test1_tuples.json
    check: ...
    list_objects: ...
  - name: test 2
    tuple_file: ./test2_tuples.json
    check: ...
    list_objects: ...
```

This follows on the work completed on the CLI: https://github.com/openfga/cli/issues/179

On VS Code, this includes:
- [ ] Do not mark `tuple_file` as invalid, both globally and in tests
- [ ] Validate tests (Checks and List objects) according to the tuples, including those in the model file
