### ISSUE TITLE
Validation error for identifiers containing the / character

### ISSUE THREAD

**Issue by mwangersjo** [openfga/vscode-ext#182]
Some examples in the docs use names such as `team:contoso/tooling`. These result in a syntax error highlighting in VS code when added to an `fga.yaml`-file. Example: 

```
name: example
model: |
  model
    schema 1.1

  type user
  type team
    relations
        define member: [user]

tuples:
- user: user:mats
  relation: member
  object: team:contoso/tooling

tests:
  - name: Test
    check:
      - user: user:mats
        object: team:contoso/tooling
        assertions:
          member: true
```

Which results in errors on the `object` fields in `tuples` and `tests`even though FGA allows for theses names. (`OpenFGAYamlValidationError`)
